# Generated by Django 5.0.3 on 2024-03-18 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('uncount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف محصول')),
                ('image', models.ImageField(upload_to='media/', verbose_name='تصویر محصول')),
                ('main_genre', models.CharField(max_length=50, verbose_name='ژانر اصلی محصول')),
                ('title', models.CharField(max_length=70, verbose_name='سربرگ محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('long_description', models.TextField(verbose_name='توضیحات بلند')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30, verbose_name='ژانر محصول')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product')),
            ],
            options={
                'verbose_name': 'ژانر محصول',
                'verbose_name_plural': 'ژانر محصولات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=30, verbose_name='نام فرستنده')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('readed_by_admin', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
