# Generated by Django 5.0.3 on 2024-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت قبل محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='next_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت بعد محصول'),
        ),
    ]
