# Generated by Django 5.0.3 on 2024-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_product_uncount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='product',
        ),
        migrations.AddField(
            model_name='genre',
            name='product',
            field=models.ManyToManyField(to='Home.product', verbose_name='ژانر محصول'),
        ),
    ]
