# Generated by Django 5.0.3 on 2024-03-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_genre_product_genre_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multi_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=30, verbose_name='ژانر محصول')),
                ('product', models.ManyToManyField(to='Home.product', verbose_name='ژانر محصول')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ محصولات',
            },
        ),
    ]
