# Generated by Django 5.0.3 on 2024-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_multi_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='مرور'),
        ),
    ]
