# Generated by Django 5.0.3 on 2024-03-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل فرستنده'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام فرستنده'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع پیام'),
        ),
        migrations.AddField(
            model_name='comment',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی فرستنده'),
        ),
    ]
