# Generated by Django 5.0.3 on 2024-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_comment_auther_remove_comment_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'کاربر دنبال کننده',
                'verbose_name_plural': 'کاربر های  دنبال کننده',
            },
        ),
    ]
