# Generated by Django 5.0.3 on 2024-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(max_length=500, verbose_name='متن کپی رایت')),
            ],
            options={
                'verbose_name': 'اطلاعات footer',
                'verbose_name_plural': 'اطلاعات footer',
            },
        ),
    ]
