# Generated by Django 5.0.3 on 2024-03-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0002_footer_information_main_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_link', models.URLField(max_length=500, verbose_name='لینک صفحه محصولات')),
                ('User_Panel_link', models.URLField(max_length=500, verbose_name='لینک صفحه پنل کاربر')),
                ('Logout_link', models.URLField(max_length=500, verbose_name='لینک صفحه خرج کاربر')),
                ('Register_link', models.URLField(max_length=500, verbose_name='لینک صفحه ثبت نام')),
                ('Login_link', models.URLField(max_length=500, verbose_name='لینک صفحه ورود کاربر')),
                ('Panel_Admin_link', models.URLField(max_length=500, verbose_name='لینک صفحه پنل ادمین')),
                ('Contact_Us_link', models.URLField(max_length=500, verbose_name='لینک صفحه ارتباط با ما')),
                ('About_Us_link', models.URLField(max_length=500, verbose_name='لینک صفحه درباره ما')),
                ('Home_link', models.URLField(max_length=500, verbose_name='لینک صفحه اصلی')),
                ('main_setting', models.BooleanField(default=False, verbose_name='تنظیمات اصلی سایت')),
            ],
            options={
                'verbose_name': 'اطلاعات footer',
                'verbose_name_plural': 'اطلاعات footer',
            },
        ),
    ]
