# Generated by Django 5.0.3 on 2024-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0003_header_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header_information',
            options={'verbose_name': 'اطلاعات Header', 'verbose_name_plural': 'اطلاعات Header'},
        ),
        migrations.AlterField(
            model_name='header_information',
            name='About_Us_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه درباره ما'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Contact_Us_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Home_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Login_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه ورود کاربر'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Logout_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه خرج کاربر'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Panel_Admin_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه پنل ادمین'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Product_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه محصولات'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='Register_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه ثبت نام'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='User_Panel_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه پنل کاربر'),
        ),
        migrations.AlterField(
            model_name='header_information',
            name='main_setting',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='تنظیمات اصلی سایت'),
        ),
    ]
