# Generated by Django 5.0.3 on 2024-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0004_alter_header_information_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header_information',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/setting/', verbose_name='لوگوی سایت'),
        ),
    ]
