# Generated by Django 5.0.3 on 2024-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0005_header_information_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(max_length=100, verbose_name='متن کوچکتر')),
                ('big_text', models.CharField(max_length=100, verbose_name='متن بزرگتر')),
                ('text', models.TextField(max_length=500, verbose_name='متن')),
                ('image', models.ImageField(upload_to='media/setting/', verbose_name='تصویر بنر')),
                ('uncount', models.BooleanField(default=False, verbose_name='تخفیف دارد / ندارد')),
            ],
            options={
                'verbose_name': 'اطلاعات بنر',
                'verbose_name_plural': 'اطلاعات بنر',
            },
        ),
    ]
