# Generated by Django 5.0.3 on 2024-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0007_slide_last_price_slide_uncount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=50, verbose_name='نام سایت')),
                ('website_information', models.TextField(verbose_name='در مورد سایت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
            ],
        ),
    ]
