# Generated by Django 5.0.3 on 2024-03-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_module', '0008_website_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website_information',
            options={'verbose_name': 'اطلاعات سایت', 'verbose_name_plural': 'اطلاعات سایت'},
        ),
    ]
